import {FURNITURE,furnish,leaveHome,useFurniture,startSleep,wakeUp} from './homes.js';
const safe=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function setupHomeUI(world,save){
 const el=document.createElement('section');el.id='home-interior';el.hidden=true;el.setAttribute('aria-label','Cottage interior');document.body.append(el);let old='';
 const status=document.createElement('aside');status.id='sleep-status';status.hidden=true;status.innerHTML='<strong></strong><span></span><button data-wake>Wake up early</button>';document.body.append(status);status.onclick=e=>{if(e.target.closest('[data-wake]')){wakeUp(world);save();refresh();}};
 el.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.exit){leaveHome(world);save();refresh();return;}if(b.dataset.sleep)startSleep(world,Number(b.dataset.sleep));if(b.dataset.furnish)furnish(world,world.state.player.insideHome,b.dataset.furnish);if(b.dataset.useFurniture)useFurniture(world,b.dataset.useFurniture);save();refresh();};
 function refresh(){
  const s=world.state,t=s.player.homeTask;status.hidden=t?.type!=='bed';if(!status.hidden){status.querySelector('strong').textContent=`🛏 Sleeping · ${Math.floor(t.remaining/25)}h ${Math.ceil(t.remaining%25*2.4)}m left`;status.querySelector('span').textContent=`Energy ${Math.round(s.player.needs?.energy||0)}%`;}const h=s.buildings.find(b=>b.id===s.player.insideHome&&b.health>0);el.hidden=!h;if(!h){old='';return;}
  const rooms=['Bedroom','Kitchen','Bathroom','Children’s room'];
  const html=`<header><div><small>YOUR COTTAGE</small><h1>Welcome inside</h1><p>${Math.floor(s.coins)} gold · Your farm continues outside</p></div><button data-exit="yes">Exit house</button></header><div class="home-floor">${rooms.map(room=>`<section class="home-room"><h2>${room}</h2><div class="home-furniture">${Object.entries(FURNITURE).filter(([,x])=>x.room===room).map(([id,x])=>{const owned=h.furniture?.includes(id),users=[s.player,...s.npcs].filter(n=>n.insideHome===h.id&&n.homeTask?.type===id);return `<article class="${owned?'furnished':'empty'}"><div class="furniture-picture" aria-hidden="true">${x.icon}</div><h3>${x.name}</h3>${owned&&id==='bed'?[6,7,8,9].map(hours=>`<button data-sleep="${hours}" ${s.player.homeTask||users.length?'disabled':''}>Sleep ${hours} hours</button>`).join(''):owned?`<button data-use-furniture="${id}" ${s.player.homeTask||users.length?'disabled':''}>${x.action}</button>`:`<button data-furnish="${id}">Furnish · ${x.price} gold</button>`}<p>${users.map(n=>`<span class="home-occupant">● ${safe(n===s.player?'You':n.name)} · ${n.homeTask.type==='bed'?Math.ceil(n.homeTask.remaining/25)+' game hours':Math.ceil(n.homeTask.remaining)+'s'}</span>`).join('')||'Available'}</p></article>`;}).join('')}</div></section>`).join('')}</div><footer>${Object.entries(s.player.needs||{}).map(([key,value])=>`<span>${key}: ${Math.round(value)}%</span>`).join(' ')}<p>Residents come home automatically for meals, rest, bathing and baby care. Sleep lasts 6–9 game hours (2½–3¾ real minutes); other activities take 8 seconds. You can sleep alone.</p></footer>`;
  if(html!==old){const top=el.scrollTop;el.innerHTML=html;el.scrollTop=top;old=html;}
 }
 return {refresh};
}
